apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $.Chart.Name }}-wallet-backend"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ $.Chart.Name }}"
    service: "{{ $.Chart.Name }}-wallet-backend"
spec:
  selector:
    matchLabels:
      app: "{{ $.Chart.Name }}"
      service: "{{ $.Chart.Name }}-wallet-backend"
  replicas: {{ .Values.lucid.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: "{{ $.Chart.Name }}"
        service: "{{ $.Chart.Name }}-wallet-backend"
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
      - name: app
        image: "{{ .Values.lucid.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
          - secretRef:
              name: "{{ $.Chart.Name }}-secrets"
        livenessProbe:
          httpGet:
            path: /live
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 1
          periodSeconds: 10
        resources:
          limits:
            memory: 8192Mi
            cpu: 1
          requests:
            cpu: 50m
            memory: 256Mi
        ports:
          - name: node
            containerPort: 3000
            protocol: TCP